version: "3"
services:
  aspnet:
    container_name: aspnet-app-example
    ports:
      - "5055:80"
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: "http://+:80"
      REDIS_HOST: "localhost"
      REDIS_PORT: 6379
  redis:
    image: redis
    container_name: aspnet-app-redis
    ports:
      - "6379:6379"
